### 创建世界用例1：成功请求
# 预期响应：返回 200 OK 和世界创建信息
POST http://localhost:5110/api/world/
Content-Type: application/json

{
  "userId":1,
  "worldName": "New World",
  "seed":"1234",
  "gameMode": 0,
  "terrainGenerationMode": 0,
  "season":0
}

### 创建世界用例2：缺少必填参数 GameMode
# 预期响应：返回 400 错误，并包含 "游戏模式不能为空" 错误
POST http://localhost:5110/api/world/
Content-Type: application/json

{
  "terrainGenerationMode": 0
}

### 删除世界用例：删除世界
# 预期响应：返回 200 OK 或成功删除的反馈信息
DELETE http://localhost:5110/api/world/1

### 获取世界列表
# 预期响应：返回 200 OK 
GET http://localhost:5110/api/world/1


