### 获取玩家信息
GET http://localhost:5110/api/player/1
Accept: application/json

# 说明：此请求用于根据玩家 ID 获取玩家信息。
# 在此示例中，玩家 ID 为 1。
# 返回值将是玩家的详细信息，或者 "Player not found" 如果玩家不存在。

### 删除玩家（失败：玩家不属于指定世界）
DELETE http://localhost:5110/api/player?userId=2&worldId=10&playerId=5
Accept: application/json

# 说明：此请求尝试删除玩家 ID 为 5 的玩家，前提是该玩家属于指定的世界 ID 10。
# 如果玩家不属于该世界，返回 "Player does not belong to the specified world" 错误。

### 删除玩家（失败：不能删除自己）
DELETE http://localhost:5110/api/player?userId=5&worldId=10&playerId=5
Accept: application/json

# 说明：此请求尝试删除玩家 ID 为 5 的玩家，且发起请求的用户 ID 也是 5。
# 由于用户不能删除自己，返回 "You cannot remove yourself" 错误。

### 删除玩家（成功）
DELETE http://localhost:5110/api/player?userId=2&worldId=10&playerId=5
Accept: application/json

# 说明：此请求尝试删除玩家 ID 为 5 的玩家，前提是该玩家属于指定的世界 ID 10，且发起删除操作的用户 ID 不是玩家自身。
# 如果删除成功，返回成功响应。
